### PR TITLE
Update Asset Documentation to 7.0

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Cody, 

there is very little to update about this tutorial. 

The part that has changed a bit more is the AssetRenderer part, but it was not covered in this tutorial. Is there another tutorial that explains how to make your content appear in asset publisher and how to control how your assets are displayed there?

I guess there must be something explaining it because AssetRenderers are also needed for the workflow, or the Recycle bin....

maybe they should be here and the others should reference this?

let me know what you think,

thank you!!

### CODE REVIEW

**Comment by codyhoag** [comment]
Hey Julio; For our 6.2 documentation, we covered Asset Renderers in the MVC learning path article [Implementing Asset Renderers](https://dev.liferay.com/develop/learning-paths/mvc/-/knowledge_base/6-2/implementing-asset-renderers). Once we start on the learning path, this info will be reintroduced for Liferay 7. 

Would you recommend we make a tutorial specific for Asset Renderers? At least until the learning path is complete (no timetable currently)? Thanks!

**Comment by juliocamarero** [comment]
mmm... I think it could make sense to have another tutorial in this section called "04-displaying-your-content-in-asset-publisher" that would explain how to do that. I like the tutorial format because they explain to developers "how to achieve something" such as "display content in asset publisher" instead of "implementing asset renderers". Would you be able to create that tutorial? or do you prefer me to send you a first version based on the learning path?

**Comment by codyhoag** [comment]
If you could send me a draft of a tutorial for that, that would be great! For the tutorial, we'll want to move away from the Guestbook focused content that was in the learning path, and focus on a 7.0 existing application, preferably. I'm not sure where to even look for that in our modules.

No rush! I know I'm a bit backed up at the moment. Thanks, Julio!

BTW, I'm going to start reviewing this PR today! Thanks for your patience!

**Comment by codyhoag** [comment]
Sent sez11a#1622 for final review. Thanks!

**Pull request closed without merging**
