### PR TITLE
More Change Lists docs

### PR DESCRIPTION
**Pull request by codyhoag**
Hey @danielkocsis; I've included four more Change List articles on this branch. Can you please review them? I've outlined what we have so far:

- Intro (reviewed; suggestions applied)
- Enabling Change Lists (reviewed; suggestions applied)
- Creating Change Lists (**REQUIRES A REVIEW**)
- Managing Change Lists (**REQUIRES A REVIEW**)
- Editing Multiple Change Lists in Parallel (**REQUIRES A REVIEW**)
- Configuring Permissions for Change Lists (**REQUIRES A REVIEW**)

This was what I had planned to write for the GA1 release. Let me know any additional info that must be included.

Thank you!

### CODE REVIEW

**Comment by danielkocsis** [comment]
Hey @codyhoag,

I like these documents, so from my side it is good to go! Please ask Dave to also take a look on them!

thanks,
Daniel

**Comment by codyhoag** [comment]
Great! I'll run them by Dave. Is there any other content you can think of that we should add?

**Comment by danielkocsis** [comment]
Right now, I think we are fine, but future changes might require changes here as well, but we'll create documentation tickets wherever needed.

**Comment by codyhoag** [comment]
Sounds good! Thanks!

**Pull request closed without merging**
